public class Aluno {
    private String nome;
    private String serie;
    
    public Aluno(String nomee, String Seriee){
        nome = nomee;
        idade = Seriee;
    }
    
    
    public void setSeie(String serie) {
        this.serie = serie;
    }

    public String getSerie() {
        return serie;
    }
    
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getNome() {
        return nome;
    }
}
